[build]
entrypoints = [
    "./src/form-config.js",
    "./src/form-router.js",
    "./src/ms-form-builder.js",
    "./src/ms-form-router.js",
    "./src/schedule-guard.js"
]
outdir = "./dist"
minify = true
target = "browser" 